[package]
name = "detection_contract"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true
detection_contract = ["src/lib.cairo"]

[profile.default]
account = "kweli"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.public.blastapi.io"

[dependencies]
starknet = "2.11.4"
